@BitmailServer_HostAddress = http://localhost:7273

POST {{BitmailServer_HostAddress}}/api/email/send
Accept: application/json

###

GET {{BitmailServer_HostAddress}}/api/email/inbox
Accept: application/json